DROP TABLE WORKS_ON;
TRUNCATE TABLE DEPT_LOCATIONS;

ALTER TABLE DEPENDENT ADD(Gender char(1));
ALTER TABLE DEPENDENT DROP COLUMN Sex;
ALTER TABLE PROJECT RENAME TO PROJECTS;
ALTER TABLE PROJECTS RENAME TO PROJECT;
ALTER TABLE EMPLOYEE CHANGE COLUMN Sex Gender char(1);
ALTER TABLE PROJECT MODIFY Pname varchar(30);

INSERT INTO EMPLOYEE (Fname, Minit, Lname, Ssn, Bdate, Address, Gender, Salary, Super_Ssn, Dno) 
VALUES ('John', 'D', 'Smith', 123456780, '1965-01-09', '731 Fondren, Houston, TX', 'M', 30000, 333445555, 5);

UPDATE EMPLOYEE SET Minit = 'X' where Salary = 30000;
DELETE FROM EMPLOYEE WHERE Gender = 'M';

