--1
SELECT * FROM Fname, Bdate,Address FROM EMPLOYEE, DEPARTMENT WHERE EMPLOYEE.Dno = DEPARTMENT.Dnumber;

--2
SELECT SUM(Salary), MAX(Salary), MAX(Salary), AVG(Salary) FROM EMPLOYEE, DEPARTMENT WHERE Dname = 'Research' AND EMPLOYEE.Dno=DEPARTMENT.Dnumber;

--3
SELECT Count(*) FROM EMPLOYEE, DEPARTMENT WHERE Dname = 'Administration' AND EMPLOYEE.Dno = DEPARTMENT.Dnumber;

--4
SELECT Pname, Pnumber, COUNT(*) FROM PROJECT, WORKS_ON WHERE PROJECT.Pnumber = WORKS_ON.Pno GROUP BY PROJECT.Pnumber;

--5
SELECT Pname, Pnumber, COUNT(*) FROM PROJECT, WORKS_ON WHERE PROJECT.Pnumber = WORKS_ON.Pno AND PROJECT.Dno=5 GROUP BY PROJECT.Pnumber;

--6
SELECT Pnumber, Dno, Lname, Address from PROJECT, DEPARTMENT, EMPLOYEE WHERE PORJECT.Plocation='Houston' AND PROJECT.Dno=DEPARTMENT.Dnumber AND DEPARTMENT.Mgr_ssn = EMPLOYEE.Ssn;

--7
SELECT  Fname, Lname, Pno, Dno from EMPLOYEE, WORKS_ON WHERE EMPLOYEE.Ssn=WORKS_ON.Essn ORDER BY Dno, Fname, Lname;

--8
SELECT Fname, Lname FROM EMPLOYEE WHERE EMPLOYEE.Super_ssn IS NULL;

--9
SELECT Fname, Lname FROM EMPLOYEE WHERE EMPLOYEE.Super_ssn = EMPLOYEE.Ssn AND EMPLOYEE.Super_ssn ='987654321';
